name = "authkit-cloudflare"
compatibility_date = "2024-08-01"
pages_build_output_dir = "out"

# Cloudflare D1 Database
# Configure in Cloudflare dashboard and set the binding and database_id
[[d1_databases]]
binding = "DB"
database_name = "authkit-production"
# database_id = "YOUR_D1_DATABASE_ID" # Set this in Cloudflare dashboard

# Cloudflare R2 Storage
# Configure in Cloudflare dashboard
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "authkit-storage"

# Cloudflare KV Store
# Configure in Cloudflare dashboard and set the namespace ID
[[kv_namespaces]]
binding = "KV"
# id = "YOUR_KV_NAMESPACE_ID" # Set this in Cloudflare dashboard

# Environment variables - Configure these in Cloudflare dashboard or Vercel
# Required for production deployment:
# - NEXT_PUBLIC_FIREBASE_API_KEY
# - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN  
# - NEXT_PUBLIC_FIREBASE_DATABASE_URL
# - NEXT_PUBLIC_FIREBASE_PROJECT_ID
# - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
# - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
# - NEXT_PUBLIC_FIREBASE_APP_ID
# - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
# - NEXT_PUBLIC_PAYPAL_CLIENT_ID
# - NEXT_PUBLIC_PAYPAL_BUSINESS_EMAIL
# - NEXT_PUBLIC_MERCADOPAGO_PUBLIC_KEY
# - MERCADOPAGO_ACCESS_TOKEN
# - NEXT_PUBLIC_CLOUDFLARE_ACCOUNT_ID
# - CLOUDFLARE_API_TOKEN
# - CLOUDFLARE_D1_DATABASE_ID
# - CLOUDFLARE_R2_BUCKET_NAME
# - NEXT_PUBLIC_RAPIDAPI_KEY
# - NEXTAUTH_SECRET
# - NEXTAUTH_URL
# - GITHUB_PERSONAL_ACCESS_TOKEN (optional)
